name: Run Shell Commands
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "job1"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo build
        run: echo "job2"
